spring:
  application:
    name: notification-hub

  profiles:
    active: local

delivery:
  worker:
    max-batch-size: 10
    fixed-delay-ms: 5000

slack:
  webhook-url: https://hooks.slack.test/webhook
